use-damage = true;
xrender-sync-fence = true;

fading = true;
fade-in-step = 0.04; 
fade-out-step = 0.04;

fade-exclude = [
  "class_g = 'slop'"   # maim
]

backend = "glx";
vsync = false;

log-level = "info";

# Радиус скругления углов в пикселях
corner-radius = 12;

# Включить скругление для рамок окон
round-borders = 1;

# Исключения (чтобы панели, меню и трей не скруглялись)
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Polybar'",
  "class_g = 'Rofi'",
  "class_g = 'dwm'"
];


blur: {
  method = "dual_kawase";
  strength = 5; # Интенсивность размытия (обычно от 1 до 10)
  background = true;
  background-frame = false;
  background-fixed = false;
}

blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "_GTK_FRAME_EXTENTS@:c",
    "class_g = 'Polybar'"
];


wintypes:
{
  normal = { fade = true; shadow = true; }
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = true; };
  dock = { shadow = true; }
  dnd = { shadow = true; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};
