use-damage = true;
xrender-sync-fence = true;

fading = true;
fade-in-step = 0.04; 
fade-out-step = 0.04;

fade-exclude = [
  "class_g = 'slop'"   # maim
]

backend = "glx";
vsync = false;

log-level = "info";

wintypes:
{
  normal = { fade = true; shadow = true; }
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = true; };
  dock = { shadow = true; }
  dnd = { shadow = true; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};
