[colors]
background = #0b0b0f 
foreground = #d4d4d4
muted = #f0ebff 
accent = #d2b1f2 

[bar/main]
width = 100%
height = 24
radius = 0

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2
line-color = ${colors.accent}

border-size = 0
padding-left = 1
padding-right = 1
module-margin = 1

font-0 = "AtkynsonMonoNF:size=12;2"

modules-left = menu-apps i3
modules-center = title 
modules-right = cpu memory pulseaudio date

cursor-click = pointer
enable-ipc = true

[module/menu-apps]
type = custom/menu

; If true, <label-toggle> will be to the left of the menu items (default).
; If false, it will be on the right of all the items.
expand-right = true

; "menu-LEVEL-N" has the same properties as "label-NAME" with
; the additional "exec" property
;
; Commands will be executed using "/bin/sh -c $COMMAND"

menu-0-0 = 
menu-0-0-exec = kitty 
menu-0-1 =  
menu-0-1-exec = chromium
menu-0-2 =  
menu-0-2-exec = thunar 
menu-0-3 = 󰀻
menu-0-3-exec = rofi -show drun 
menu-0-4 = 
menu-0-4-exec = ~/.config/rofi/scripts/menu.sh

; Available tags:
;   <label-toggle> (default) - gets replaced with <label-(open|close)>
;   <menu> (default)
; If expand-right is true, the default will be "<label-toggle><menu>" and the
; other way around otherwise.
; Note that if you use <label-toggle> you must also include
; the definition for <label-open>
; format = <label-toggle><menu>

label-open = 󰣇 
label-close = 󰣇 

; Optional item separator
; Default: none
label-separator = "  "

[module/pulseaudio]
type = internal/pulseaudio

; Sink to be used, if it exists (find using `pacmd list-sinks`, name field)
; If not, uses default sink
; sink = alsa_output.pci-0000_12_00.3.analog-stereo

; Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
; Default: true
use-ui-max = false

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 5

; Reverses the increment/decrement on scroll event. Set this to true if you are
; using natural scrolling option on your touchpad.
; New in version 3.7.0
; Default: false
reverse-scroll = false
; Available tags:
;   <label-volume> (default)
;   <ramp-volume>
;   <bar-volume>
format-volume = <ramp-volume>

; Available tags:
;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
;format-muted = <label-muted>

; Available tokens:
;   %percentage% (default)
;   %decibels%
;label-volume = %percentage%%

; Available tokens:
;   %percentage% (default)
;   %decibels%
label-muted = 󰸈 
label-muted-foreground = #666

; Only applies if <ramp-volume> is used
ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀 
ramp-volume-2 = 󰕾

; Right and Middle click
click-right = pavucontrol
; click-middle =


[module/cava]
type = custom/script
tail = true
exec = $HOME/.config/polybar/scripts/cava.sh
format = <label>
format-font = 5
label = %output%
label-foreground = #c5a9eb

[module/i3]
type = internal/i3

format = <label-state> <label-mode>

label-mode =  %mode%
label-focused = %name%
label-focused-foreground = ${colors.accent}
label-focused-padding = 1

label-unfocused = %name%
label-unfocused-foreground = ${colors.muted}
label-unfocused-padding = 1

label-visible = %name%
label-visible-padding = 1

label-urgent = %name%
label-urgent-foreground = #f38ba8
label-urgent-padding = 1

[module/title]
type = internal/xwindow

format = <label>
label =  < %title% >
label-maxlen = 30
label-foreground = ${colors.muted}

[module/cpu]
type = internal/cpu
interval = 2

format = <label>
label =   %percentage:2%%
label-foreground = ${colors.foreground}

[module/memory]
type = internal/memory
interval = 2

format = <label>
label =   %percentage_used:2%%
label-foreground = ${colors.foreground}

[module/date]
type = internal/date
interval = 1

date = %H:%M
label = %date%
label-foreground = ${colors.accent}
