[colors]
background = #99000000
 
foreground = #d4d4d4
muted = #f0ebff 
accent = #f0f0f0 

[bar/main]
width = 100%
height = 24
radius = 6


background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2
line-color = ${colors.accent}
override-redirect = true
border-left-size = 85%
border-right-size = 0.6%
border-top-size = 8px

top = true

spacing = 1
border-size = 0
padding-left = 1
padding-right = 2
module-margin = 7px

font-0 = "AtkynsonMonoNF:size=12;2"

modules-left = cpu memory disk

cursor-click = pointer
enable-ipc = true


[bar/main1]
wplayer-mpris-simpleidth = 100%
height = 24
radius = 6

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2
line-color = ${colors.accent}
override-redirect = true
border-left-size = 0.6%
border-right-size = 85%
border-top-size = 8px
padding-left = 2
padding-right = 2

top = true

font-0 = "AtkynsonMonoNF:size=12;2"

modules-left = date 

cursor-click = pointer
enable-ipc = true

[bar/main2]
width = 100%
height = 24
radius = 6

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2
line-color = ${colors.accent}
override-redirect = true
border-left-size = 30%
border-right-size = 30%
border-top-size = 8px

top = true

spacing = 1
border-size = 0
padding-left = 2
padding-right = 2
module-margin = 4px

font-0 = "AtkynsonMonoNF:size=12;2"

modules-left = menu-apps 
modules-center = i3
modules-right = network
cursor-click = pointer
enable-ipc = true

[module/network]
type = internal/network
interface = wlan0
interval = 3

format-connected = <label-connected>
label-connected = %downspeed:9%

format-disconnected = <label-disconnected>
label-disconnected = нет сети

[module/menu-apps]
type = custom/menu

; If true, <label-toggle> will be to the left of the menu items (default).
; If falsepe it will be on the right of all the items.
expand-right = true

; "menu-LEVEL-N" has the same properties as "label-NAME" with
; the additional "exec" property
;
; Commands will be executed using "/bin/sh -c $COMMAND"

menu-0-0 = 
menu-0-0-exec = kitty 
menu-0-1 =  
menu-0-1-exec = chromium
menu-0-2 =  
menu-0-2-exec = thunar 
menu-0-3 = 󰀻
menu-0-3-exec = rofi -show drun 
menu-0-4 =  ‎ 
menu-0-4-exec = ~/.config/rofi/scripts/menu.sh

; Available tags:
;   <label-toggle> (default) - gets replaced with <label-(open|close)>
;   <menu> (default)
; If expand-right is true, the default will be "<label-toggle><menu>" and the
; other way around otherwise.
; Note that if you use <label-toggle> you must also include
; the definition for <label-open>
; format = <label-toggle><menu>

label-open = 󰣇 ‎  
label-close = 󰣇 ‎   

; Optional item separator
; Default: none


[module/i3]
type = internal/i3

format = <label-state> <label-mode>

label-mode =  ‎ 
label-focused = 
label-focused-foreground = ${colors.accent}
label-focused-padding = 1

label-unfocused = 
label-unfocused-foreground = ${colors.muted}
label-unfocused-padding = 1

label-visible = %name%
label-visible-padding = 1

label-urgent = 
label-urgent-foreground = #f38ba8
label-urgent-padding = 1

[module/title]
type = internal/xwindow

format = <label>
label =  < %title% >
label-maxlen = 30
label-foreground = ${colors.muted}

[module/cpu]
type = internal/cpu
interval = 2

format = <label>
label =   %percentage:2%%
label-foreground = ${colors.foreground}

[module/memory]
type = internal/memory
interval = 2

format = <label>
label =   %percentage_used:2%%
label-foreground = ${colors.foreground}

[module/disk]
type = internal/fs

; Точка монтирования вашего диска (можно указать несколько через пробел)
mount-0 = /

; Интервал обновления в секундах
interval = 30

; Показывать только если диск смонтирован
fixed-values = true

; Формат вывода при нормальной работе
format-mounted = <label-mounted>
format-mounted-prefix = "💾 "
format-mounted-prefix-foreground = #F0C674

; Что именно выводить (%free% — свободное место, %total% — всего)
label-mounted =  %free% 

; Формат вывода, если диск не найден
format-unmounted = <label-unmounted>
label-unmounted = %mountpoint% не найден
label-unmounted-foreground = #707880


[module/date]
type = internal/date
interval = 1

date = %c
label = %date%
label-foreground = ${colors.accent}
